"""empty message

Revision ID: 63f6c3c8d247
Revises: dd3fca520474
Create Date: 2021-03-24 22:14:34.727115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f6c3c8d247'
down_revision = 'dd3fca520474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unread', 'read', 'action_taken', name='notificationstatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ithriv_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_action_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('notification_action_id', sa.Integer(), nullable=True),
    sa.Column('date_notification_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_action_id'], ['notification_action.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_action_taken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('notification_action_id', sa.Integer(), nullable=True),
    sa.Column('date_action_taken', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_action_id'], ['notification_action.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_action_taken')
    op.drop_table('notification_action_sent')
    op.drop_table('notification')
    op.drop_table('notification_action')
    # ### end Alembic commands ###
